---
- name: Manage Docker Containers
  hosts: localhost
  gather_facts:  false
  vars:
    compose_state: present
    keycloak_state: present
  tasks:
    
#    - name: Show facts
#      debug:
#        var: ansible_facts

    - name: Create a network
      docker_network:
        name: keycloak_net

    - name: Create and start services
      docker_compose:
        project_src: ~/codesenju/keycloak_grafana
        state: "{{ compose_state }}"
      notify:
        -   Wait for keycloak server
#      register: output  
#    - debug:
#        var: output

    - name: Get info on container
      docker_container_info:
        name: keycloak
      register: keycloak_result

#    - name: Does container exist?
#      debug:
#        msg: "The container {{ 'exists' if keycloak_result.exists else 'does not exist' }}"

#    - name: Print information about container
#      debug:
#        var: keycloak_result.container
#      when: keycloak_result.exists

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers

    - name: Configure Keycloak Server
      import_tasks: keycloak.yml
      when: keycloak_result.exists

  handlers:
    - name: Wait for keycloak server
      wait_for:
        timeout: 20
      delegate_to: localhost
      when: keycloak_result.exists
      